In [5]:
import pandas as pd
import json
import constants

In [6]:
nobs_url_base = 'http://hazy.pmel.noaa.gov:8140/'
datasets = 'datasets.json'
if datasets is not None:
    with open(datasets) as discovery_stream:
        datasets_json = json.load(discovery_stream)

In [7]:
dfs = {}
for variable in datasets_json:
    nobs_sources = datasets_json[variable]['datasets']
    adf = None
    for source in nobs_sources:
        url = nobs_url_base + source[source.index('/erddap')+1:]
        df = pd.read_csv(url+'.csv', skiprows=[1])
        if adf is None:
            adf = df 
        else:
            adf = pd.concat([adf, df])
    dfs[variable] = adf

In [16]:
sdf = dfs['salinity']
sdf

,time,profile_id,wmo_platform_code,site_code,depth,PRES_DM,PSAL_DM,TEMP_DM,PRES,PRES_QC,PSAL,PSAL_QC,TEMP,TEMP_QC
0,2004-06-01T00:00:00Z,0,28401,KEO,11136,4176.0,3132,4176.0,4176.0,4176.0,3052,3132,4096.0,4176.0
1,2004-07-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696,8928.0,8928.0,8928.0,5952,6696,8184.0,8928.0
2,2004-08-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696,8928.0,8928.0,8928.0,5952,6696,8184.0,8928.0
3,2004-09-01T00:00:00Z,0,28401,KEO,23040,8640.0,6480,8640.0,8640.0,8640.0,5760,6480,7920.0,8640.0
4,2004-10-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696,8928.0,8928.0,8928.0,5952,6696,8184.0,8928.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,2020-09-01T00:00:00Z,0,53006,12s80.5e,3592,NaN,3592,NaN,NaN,NaN,3592,3592,NaN,NaN
987,2020-10-01T00:00:00Z,0,53006,12s80.5e,695,NaN,695,NaN,NaN,NaN,695,695,NaN,NaN
988,2020-11-01T00:00:00Z,0,53006,12s80.5e,2194,NaN,2194,NaN,NaN,NaN,2194,2194,NaN,NaN
989,2020-12-01T00:00:00Z,0,53006,12s80.5e,2803,NaN,2803,NaN,NaN,NaN,2803,2803,NaN,NaN
990,2021-01-01T00:00:00Z,0,53006,12s80.5e,182,NaN,182,NaN,NaN,NaN,182,182,NaN,NaN

In [18]:
tdf = dfs['temperature']
tdf

,time,profile_id,wmo_platform_code,site_code,depth,PRES_DM,PSAL_DM,TEMP_DM,PRES,PRES_QC,PSAL,PSAL_QC,TEMP,TEMP_QC
0,2004-06-01T00:00:00Z,0,28401,KEO,11136,4176.0,3132.0,4176,4176.0,4176.0,3052.0,3132.0,4096,4176
1,2004-07-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
2,2004-08-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
3,2004-09-01T00:00:00Z,0,28401,KEO,23040,8640.0,6480.0,8640,8640.0,8640.0,5760.0,6480.0,7920,8640
4,2004-10-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,2020-09-01T00:00:00Z,0,53006,12s80.5e,8632,NaN,NaN,8632,NaN,NaN,NaN,NaN,8632,8632
420,2020-10-01T00:00:00Z,0,53006,12s80.5e,1913,NaN,NaN,1913,NaN,NaN,NaN,NaN,1913,1913
421,2020-11-01T00:00:00Z,0,53006,12s80.5e,5169,NaN,NaN,5169,NaN,NaN,NaN,NaN,5169,5169
422,2020-12-01T00:00:00Z,0,53006,12s80.5e,5617,NaN,NaN,5617,NaN,NaN,NaN,NaN,5617,5617
423,2021-01-01T00:00:00Z,0,53006,12s80.5e,303,NaN,NaN,303,NaN,NaN,NaN,NaN,303,303

In [23]:
ndf = sdf[['time','profile_id','wmo_platform_code','site_code','depth','PRES','PSAL']]
ndf = pd.merge(ndf, tdf[['time','profile_id','wmo_platform_code','site_code','TEMP',]])
# ndf['TEMP'] = tdf['TEMP']
# ndf['TEMP_QC'] = tdf['TEMP_QC']
# ndf['TEMP_DM'] = tdf['TEMP_DM']
ndf

,time,profile_id,wmo_platform_code,site_code,depth,PRES,PSAL,TEMP
0,2004-06-01T00:00:00Z,0,28401,KEO,11136,4176.0,3052,4096
1,2004-07-01T00:00:00Z,0,28401,KEO,23808,8928.0,5952,8184
2,2004-08-01T00:00:00Z,0,28401,KEO,23808,8928.0,5952,8184
3,2004-09-01T00:00:00Z,0,28401,KEO,23040,8640.0,5760,7920
4,2004-10-01T00:00:00Z,0,28401,KEO,23808,8928.0,5952,8184
...,...,...,...,...,...,...,...,...
1356,2020-09-01T00:00:00Z,0,53006,12s80.5e,3592,NaN,3592,8632
1357,2020-10-01T00:00:00Z,0,53006,12s80.5e,695,NaN,695,1913
1358,2020-11-01T00:00:00Z,0,53006,12s80.5e,2194,NaN,2194,5169
1359,2020-12-01T00:00:00Z,0,53006,12s80.5e,2803,NaN,2803,5617
1360,2021-01-01T00:00:00Z,0,53006,12s80.5e,182,NaN,182,303

In [25]:
with constants.postgres_engine.connect() as conn:
    ndf.to_sql('nobs', con=conn, index=False)

In [9]:
dfs['temperature']

,time,profile_id,wmo_platform_code,site_code,depth,PRES_DM,PSAL_DM,TEMP_DM,PRES,PRES_QC,PSAL,PSAL_QC,TEMP,TEMP_QC
0,2004-06-01T00:00:00Z,0,28401,KEO,11136,4176.0,3132.0,4176,4176.0,4176.0,3052.0,3132.0,4096,4176
1,2004-07-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
2,2004-08-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
3,2004-09-01T00:00:00Z,0,28401,KEO,23040,8640.0,6480.0,8640,8640.0,8640.0,5760.0,6480.0,7920,8640
4,2004-10-01T00:00:00Z,0,28401,KEO,23808,8928.0,6696.0,8928,8928.0,8928.0,5952.0,6696.0,8184,8928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,2020-09-01T00:00:00Z,0,53006,12s80.5e,8632,NaN,NaN,8632,NaN,NaN,NaN,NaN,8632,8632
420,2020-10-01T00:00:00Z,0,53006,12s80.5e,1913,NaN,NaN,1913,NaN,NaN,NaN,NaN,1913,1913
421,2020-11-01T00:00:00Z,0,53006,12s80.5e,5169,NaN,NaN,5169,NaN,NaN,NaN,NaN,5169,5169
422,2020-12-01T00:00:00Z,0,53006,12s80.5e,5617,NaN,NaN,5617,NaN,NaN,NaN,NaN,5617,5617
423,2021-01-01T00:00:00Z,0,53006,12s80.5e,303,NaN,NaN,303,NaN,NaN,NaN,NaN,303,303

In [10]:
with constants.postgres_engine.connect() as conn:
    dfs['salinity'].to_sql('salinity_nobs', con=conn, index=False)
with constants.postgres_engine.connect() as conn:
    dfs['temperature'].to_sql('temperature_nobs',con=conn, index=False)